on: [push, pull_request]

name: CI

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: mkdir build
        shell: bash
      - run: cmake ..
        working-directory: build
      - run: cmake --build build
